DOCS_FOLDER = ./docs
BACKEND_FOLDER = ./backend

# Call makefile in docs folder
documentation:
	$(MAKE) -C $(DOCS_FOLDER)

# Call makefile in backend folder
backend:
	$(MAKE) -C $(BACKEND_FOLDER)

# Clean the backend and docs folder
clean:
	$(MAKE) -C $(DOCS_FOLDER) clean